### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [Nukesor/spacesurvival#1]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by Nukesor** [comment]
We need the functionality for the `uuid` package.
As soon as this package doesn't depend on rustc-serialze anymore we don't need it either.

**Comment by dtolnay** [comment]
Thanks for the update @Nukesor. The latest version of `uuid` supports serializing and deserializing `Uuid` with Serde. If that is not what you mean, could you please make sure they have an issue open to address what you are waiting for?
